### PR TITLE
EE-1209 and EE-1216: Table template revision. Redoing all tables on p…

### PR DESCRIPTION
**Pull request by danieltruong**
…roject details tab.

To test this code, go to any project details tab. Castle is a good project that has all three of the tables. Ajax is good for testing pagination.

### CODE REVIEW

**Review by mtCarto — CHANGES_REQUESTED** [review]
Found a couple bugs in modified tables
 - Adv Search styling isn't applied correctly for most pages with that component
 - Featured docs: use next page button, docs list gets cleared and you appear to be stuck on page 1 (page number is 2 in URL, so page reloads in bad state).

**Comment by BcGovNeal** [comment]
I'm noticing the same issue with the search component.  I'm not able to re-produce the pagination issue though

**Comment by danieltruong** [comment]
> Found a couple bugs in modified tables
> 
> * Adv Search styling isn't applied correctly for most pages with that component
> * Featured docs: use next page button, docs list gets cleared and you appear to be stuck on page 1 (page number is 2 in URL, so page reloads in bad state).

cf0cb43 and 3ecc6e5

**Review by mtCarto — APPROVED** [review]

**Review by BcGovNeal — CHANGES_REQUESTED** [review]
I'm now noticing that the `currentPage` URL param isn't working on the Documents tab for a project.  If I navigate away from page 1 and refresh then it puts me back at page 1 even though the URL param is different.

To reproduce:

1. Go to Ajax Mine (for example) details
2. Go to Documents tab.
3. Navigate to page 2 on the documents table
4. Refresh browser
5. Now you're back on page 1 even though the URL still says page 2

Expected Behaviour
The documents table should be on page 2

**Comment by danieltruong** [comment]
> I'm now noticing that the `currentPage` URL param isn't working on the Documents tab for a project. If I navigate away from page 1 and refresh then it puts me back at page 1 even though the URL param is different.
> 
> To reproduce:
> 
> 1. Go to Ajax Mine (for example) details
> 2. Go to Documents tab.
> 3. Navigate to page 2 on the documents table
> 4. Refresh browser
> 5. Now you're back on page 1 even though the URL still says page 2
> 
> Expected Behaviour
> The documents table should be on page 2

I have not done any edits to the Documents tab. The changes I have made are only on the three tables in the project details tab. The bug you have found is an existing bug that will be addressed later this sprint but as nothing to do with my ticket.

**Review by BcGovNeal — APPROVED** [review]

**Pull request merged**
